Models/Video.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace bds_site_web_version7_.Models;

public partial class Video
{
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public string Id { get; set; } = null!;
    [StringLength(255,ErrorMessage ="le nom de la vidéo ne doit pas excéder 255 caractères")]
    public string NomVideo { get; set; } = null!;

    public string TailleVideo { get; set; } = null!;

    public string ExtensionVideo { get; set; } = null!;
    
    public string CheminVideo { get; set; } = null!;

    public DateTime DateCreationVideo { get; set; }
    [NotMapped]
    public IFormFile formFile { get; set; }
}

Controllers/VideosController.cs
using bds_site_web_version7_.Models;
using bds_site_web_version7_.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace bds_site_web_version7_.Controllers
{
    [Authorize]
    public class VideosController : Controller
    {
        SiteWebBdsDbContext _context;
        IFileUpload _fileUpload;
        public VideosController(SiteWebBdsDbContext context,IFileUpload fileUpload)
        {
            _context = context;
            _fileUpload = fileUpload;
        }

        public async Task<IActionResult> Index()
        {
            return _context.Videos != null ?
                        View(await _context.Videos.ToListAsync()) :
                        Problem("Entity set 'SiteWebBdsDbContext.Videos'  is null.");
        }

        // GET: Video/Details/5
        public async Task<IActionResult> Details(string? id)
        {
            if (id == null || _context.Videos == null)
            {
                return NotFound();
            }

            var video = await _context.Videos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (video == null)
            {
                return NotFound();
            }

            return View(video);
        }

        // GET: Video/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST:Video/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Video video)
        {
            if (ModelState.IsValid)
            {
                var fileName = _fileUpload.uploadVideo(video.formFile);
                video.CheminVideo = fileName;
                video.NomVideo = fileName;
                video.TailleVideo = "ddd";
                video.ExtensionVideo = "dddd";
                video.TailleVideo = "ddds";
                _context.Add(video);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            } 
            
            return View(video);
        }

        // GET: Video/Edit/5
        public async Task<IActionResult> Edit(string? id)
        {
            if (id == null || _context.Videos == null)
            {
                return NotFound();
            }

            var video = await _context.Videos.FindAsync(id);
            if (video == null)
            {
                return NotFound();
            }
            return View(video);
        }

        // POST: Video/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, Video video)
        {
            if (id != video.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(video);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VideosExists(video.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(video);
        }

        // GET: Video/Delete/5
        public async Task<IActionResult> Delete(string? id)
        {
            if (id == null || _context.Videos == null)
            {
                return NotFound();
            }

            var video = await _context.Videos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (video == null)
            {
                return NotFound();
            }

            return View(video);
        }

        // POST: Video/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Videos == null)
            {
                return Problem("Entity set 'SiteWebBdsDbContext.Videos'  is null.");
            }
            var video = await _context.Videos.FindAsync(id);
            if (video != null)
            {
                _context.Videos.Remove(video);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VideosExists(string id)
        {
            return (_context.Videos?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }

}

Views/Videos/Create.cshtml
@{
    Layout = "~/Views/Administration/_Layout.cshtml";
    ViewData["Title"] = "Video";
}
@model bds_site_web_version7_.Models.Video
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] </title>
    <!--<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />-->
    <!--- <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />-->
    <link rel="stylesheet" href="~/css/Create.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bds_site_web.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <div class="container-title">
            <h1>Enregistrer une video </h1>
        </div>

        <form class="form" asp-controller="Videos" asp-action="Create" method="post" enctype="multipart/form-data"> 
            <div class="cv-file"><input type="file" required class="input-button" asp-for="formFile" /></div>

            <div class="form_submit"> <button class="submit-button">Enregistrer</button></div>
        </form>

    </div>
</body>
</html>

Views/Videos/Delete.cshtml
@using bds_site_web_version7_.Models;
@model Video

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Departementecole</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomVideo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomVideo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreationVideo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreationVideo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Videos/Details.cshtml
@using bds_site_web_version7_.Models;
@model Video

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>video</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomVideo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomVideo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreationVideo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreationVideo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Videos/Edit.cshtml
@using bds_site_web_version7_.Models;
@model Video

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Video</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="NomVideo" />
            <div class="form-group">
                <label asp-for="NomVideo" class="control-label"></label>
                <input asp-for="NomVideo" class="form-control" />
                <span asp-validation-for="NomVideo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateCreationVideo" class="control-label"></label>
                <input asp-for="DateCreationVideo" class="form-control" />
                <span asp-validation-for="DateCreationVideo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Videos/Index.cshtml
@using bds_site_web_version7_.Models;
@model IEnumerable<Video>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NomVideo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NomVideo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DateCreationVideo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateCreationVideo)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Videos/Update.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}